let datatable = [
    [
      { type: 'string', label: 'Task ID' },
      { type: 'string', label: 'Task Name' },
      { type: 'date', label: 'Start Date' },
      { type: 'date', label: 'End Date' },
      { type: 'number', label: 'Duration' },
      { type: 'number', label: 'Percent Complete' },
      { type: 'string', label: 'Dependencies' },
    ],
    [
      'Обучение 1',
      'Обучение JS, HTML и CSS',
      new Date(2020, 3, 6),
      new Date(2020, 5, 6),
      null,
      100,
      null,
    ],
    [
      'Обучение 2',
      'Обучение React',
      new Date(2020, 4, 20),
      new Date(2020, 5, 10),
      null,
      // 1 * 24 * 60 * 60 * 1000,
      80,
      'Обучение 1',
    ],
    [
      'Создание 1',
      'Создание списка дел',
      new Date(2020, 5, 8),
      new Date(2020, 5, 15),
      null,
      // 1 * 24 * 60 * 60 * 1000,
      100,
      'Обучение 1, Обучение 2',
    ],
    [
      'Создание 2',
      'Создание календаря',
      new Date(2020, 5, 16),
      new Date(2020, 5, 20),
      null,
      // 3 * 24 * 60 * 60 * 1000,
      80,
      'Обучение 1, Обучение 2',
    ],
    [
      'Создание 3',
      'Создание графика Ганта',
      new Date(2020, 5, 20),
      new Date(2020, 5, 22),
      null,
      // 1 * 24 * 60 * 60 * 1000,
      20,
      'Обучение 1, Обучение 2',
    ],
];

export default datatable;
